version: "2.3"
services: 
  terminal:
    container_name: yolact
    build: .
    command: lxterminal
    runtime: nvidia
    privileged: true
    network_mode: host
    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - root:/root

volumes: 
  root:
